import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'assets');
mkdirSync(assets, { recursive: true });
const args = process.argv.slice(2);
const option = (name) => {
  const index = args.indexOf(name);
  if (index < 0) return undefined;
  if (!args[index + 1] || args[index + 1].startsWith('--')) throw new Error(`Missing value for ${name}`);
  return args[index + 1];
};

const photo = option('--photo');
if (photo) {
  // Canvas is only needed when changing the portrait. Normal builds use portrait.txt.
  const work = mkdtempSync(join(tmpdir(), 'tav0dev-portrait-'));
  try {
    const data = readFileSync(resolve(photo)).toString('base64');
    const type = photo.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';
    const template = readFileSync(join(root, 'scripts', 'portrait.html'), 'utf8');
    const page = join(work, 'portrait.html');
    writeFileSync(page, template.replace('__PHOTO_DATA_URL__', `data:${type};base64,${data}`));
    const output = execFileSync(option('--browser') || 'chromium', [
      '--headless', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage',
      '--disable-background-networking', '--no-first-run', '--no-default-browser-check',
      `--user-data-dir=${join(work, 'browser')}`, '--virtual-time-budget=2000',
      '--dump-dom', pathToFileURL(page).href,
    ], { encoding: 'utf8', timeout: 20000, maxBuffer: 8 * 1024 * 1024, stdio: ['ignore', 'pipe', 'pipe'] });
    const result = output.match(/<pre id="result">([^<]+)<\/pre>/);
    if (!result) throw new Error('The browser did not return an ASCII portrait.');
    const rows = JSON.parse(result[1]);
    if (!Array.isArray(rows) || rows.length !== 82 || rows.some(row => typeof row !== 'string' || row.length !== 120)) {
      throw new Error('Unexpected ASCII portrait dimensions.');
    }
    writeFileSync(join(assets, 'portrait.txt'), `${rows.map(row => row.trimEnd()).join('\n')}\n`);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

const portrait = readFileSync(join(assets, 'portrait.txt'), 'utf8').trimEnd().split('\n');
const escape = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const mono = 'ui-monospace, SFMono-Regular, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace';
const text = (x, y, value, size = 15, fill = '#c7d5e2', attrs = '') =>
  `<text x="${x}" y="${y}" font-size="${size}" fill="${fill}" ${attrs}>${escape(value)}</text>`;
const ink = '#8bc6df';
const gold = '#d6b981';

function ascii(x, y, cellWidth, lineHeight, size) {
  // Position each visible run explicitly. SVG whitespace handling must not move
  // the face's features when a row starts with spaces or contains empty cells.
  return `<g fill="url(#portrait-ink)" font-size="${size}" font-weight="600">${portrait.flatMap((row, index) =>
    [...row.matchAll(/\S+/g)].map(match =>
      `<text x="${x + match.index * cellWidth}" y="${y + index * lineHeight}" textLength="${match[0].length * cellWidth}" lengthAdjust="spacingAndGlyphs">${escape(match[0])}</text>`)
  ).join('\n')}</g>`;
}

function shell(width, height, content) {
  return `<!-- Generated by scripts/build-profile.mjs. Edit the generator, then rebuild. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title description">
  <title id="title">Gustavo de Oliveira — AI Engineer</title>
  <desc id="description">ASCII portrait of Gustavo de Oliveira, based on his photograph. AI Engineer and co-founder at Outpost Technologies in São Paulo, Brazil. Builds agentic AI, RAG, and products using Python, TypeScript, SQL, and AWS.</desc>
  <defs>
    <linearGradient id="portrait-ink" x1="0" y1="70" x2="0" y2="480" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#d2e5ef"/><stop offset="0.65" stop-color="#9cbad0"/><stop offset="1" stop-color="#7093af"/>
    </linearGradient>
  </defs>
  <rect x="0.5" y="0.5" width="${width - 1}" height="${height - 1}" rx="12" fill="#0d1117" stroke="#303943"/>
  <path d="M1 47H${width - 1}" stroke="#26323d"/>
  <circle cx="23" cy="24" r="4" fill="#617a8a"/><circle cx="39" cy="24" r="4" fill="#8c9fa7"/><circle cx="55" cy="24" r="4" fill="#b6c5c8"/>
  <g font-family="${mono}">
    ${text(77, 29, '~/tav0dev · profile', 12, '#92a6b7')}
    ${content}
  </g>
</svg>
`;
}

const fields = [
  ['Name', 'Gustavo de Oliveira'], ['Role', 'AI Engineer / Co-Founder'],
  ['Focus', 'Agentic AI · RAG · Products'], ['Based', 'São Paulo, Brazil'],
];
const stack = [
  ['Languages', 'Python · TypeScript · SQL'], ['AI', 'OpenAI APIs · PyTorch'],
  ['Data', 'PostgreSQL · Supabase'], ['Cloud', 'AWS · Vercel · Cloudflare'],
];
const row = (y, label, value, x = 424, valueX = 552, size = 15) =>
  `${text(x, y, `${label}:`, size, gold)}${text(valueX, y, value, size)}`;
const desktop = [
  ascii(26, 81, 3.0, 4.8, 6.0),
  text(26, 506, 'GUSTAVO DE OLIVEIRA', 12, '#92a6b7', 'letter-spacing="2"'),
  text(424, 89, 'tav0dev@github', 19, ink, 'font-weight="600"'),
  text(424, 112, '──────────────────────────────────────', 15, '#3b5062'),
  ...fields.map(([label, value], index) => row(144 + index * 27, label, value)),
  text(424, 277, '── Build', 13, ink),
  ...stack.map(([label, value], index) => row(308 + index * 27, label, value)),
  text(424, 428, '── Reach', 13, ink),
  row(458, 'LinkedIn', '/in/tav0dev'), row(485, 'Email', 'gusdeoliveira.dev@gmail.com'),
  ...['#7093af', '#8bc6df', '#d6b981', '#91b9a0', '#c7d5e2', '#7e93a8', '#a69cb5', '#d0a09b'].map((color, index) =>
    `<rect x="${424 + index * 24}" y="505" width="24" height="9" fill="${color}"/>`),
  text(973, 29, 'AI / DATA / PRODUCT', 11, '#92a6b7', 'text-anchor="end"'),
].join('\n');
writeFileSync(join(assets, 'profile.svg'), shell(1000, 540, desktop));

const compactFields = [
  ['Role', 'AI Engineer / Co-Founder'], ['Focus', 'Agentic AI · RAG · Products'],
  ['Based', 'São Paulo, Brazil'], ['Languages', 'Python · TypeScript · SQL'],
  ['Cloud', 'AWS · Supabase · Vercel'],
];
const mobile = [
  ascii(117, 74, 3.0, 4.8, 6.0),
  text(40, 500, 'tav0dev@github', 23, ink, 'font-weight="600"'),
  text(40, 533, 'Gustavo de Oliveira', 29, '#e1e9ef', 'font-weight="600"'),
  ...compactFields.map(([label, value], index) => row(578 + index * 33, label, value, 40, 173, 17)),
  text(40, 744, 'gusdeoliveira.dev@gmail.com', 17, '#92a6b7'),
].join('\n');
writeFileSync(join(assets, 'profile-mobile.svg'), shell(600, 776, mobile));
console.log('Built assets/profile.svg and assets/profile-mobile.svg');
